quarkus.swagger-ui.path=/apis
quarkus.swagger-ui.always-include=true

quarkus.http.cors=true
quarkus.http.port=${PORT}
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.exposed-headers=*
quarkus.http.cors.access-control-max-age=24h
quarkus.http.cors.access-control-allow-credentials=true

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.smallrye-jwt.enabled=true

quarkus.http.auth.permission.auth-permit.paths=/auth/*
quarkus.http.auth.permission.auth-permit.policy=permit
quarkus.http.auth.permission.authenticated.paths=/users/*,/movies/*
quarkus.http.auth.permission.authenticated.policy=authenticated


mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}


mp.jwt.verify.issuer=${JWT_ISSUER}

quarkus.log.level=INFO
quarkus.log.category."io.smallrye.jwt".level=DEBUG

external.api.base-url=${EXTERNAL_API_BASE_URL}